### ISSUE TITLE
Unable to specify Node.js version for my remote function

### ISSUE THREAD

**Issue by ghoullier** [WarpJS/beta#10]
I cannot specify the version of Node.js for my cloud function.

"engines" and "engineStrict" entries in my package.json file seems not to be interpreted

package.json
```json
{
  "name": "warpjs-webpack-template",
  "version": "1.0.0",
  "scripts": {
    "start": "webpack-dev-server --open",
    "build": "webpack --progress --mode=production",
    "predeploy": "yarn build",
    "deploy": "warp-deploy --asset-dir=dist ."
  },
  "dependencies": {
    "@warpjs/engine": "^1.1.0",
    "@warpjs/warp": "^2.0.1"
  },
  "devDependencies": {
    "@warpjs/webpack-plugin": "^1.1.0",
    "clean-webpack-plugin": "^3.0.0",
    "copy-webpack-plugin": "^5.1.1",
    "html-webpack-plugin": "^3.2.0",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "engines": {
    "node": ">=12"
  },
  "engineStrict": true
}
```

index.js 
```js
// import WarpJS
import { defaultWarper as warper } from "@warpjs/warp";
import engine from "@warpjs/engine";

// init WarpJS
engine.init({ config: { logging: "info" } });

engine.setErrorHandler(function(error) {
  console.error(error.name + ": " + error.message);
});

// warp function
const hello = name => {
  return `Hello ${name} from Node.js ${process.version} 👋`;
};

// on load, call function with WarpJS
warper.call(hello, "World").then(response => {
  result.innerHTML = JSON.stringify(response);
});
```

Local
```
"Hello World from Node.js v12.14.1 👋"
```

Cloud
```
"Hello World from Node.js v8.16.0 👋"
```

There is no restriction in WarpJS documentation about Node.js  (ie: "Install Node.js latest 8.x or above (which can be checked by running node -v)")

**Comment by jpl-scale** [comment]
Thank you for your report. Your feedback is very important for us to plan future development.
We plan to add features controlling the serverless deployment as soon as we leave the beta program. Parameters like engine version, ram, timeout, location and so on will be added progressively.

**Comment by jpl-scale** [comment]
@NicolasPennec could you please add the restriction in the documentation and leave this issue open for the enhancement part?

**Comment by ghoullier** [comment]
Thanks for your reply!

**Comment by jpl-scale** [comment]
We have documented the deployment environment for the beta program in the WarpJS console.
