### ISSUE TITLE
"Build '<SOME_ID>' has not been deployed" with npm run start

### ISSUE THREAD

**Issue by dezmou** [WarpJS/beta#18]
Hello 

I am trying the hello-world project from github, 

The only modifications I've done are : 

 - Setting my userId in the webpack config 
 - modifying the start script in package.json to be able to run the script on a remote machine

`"start": "webpack-dev-server  --host 0.0.0.0 --disableHostCheck",`

Then in my browser this XHR call to : 

https://v1.api.starbase.warpjs.com//engine/get-config/4TX6kuAsEVKjfJ7ogpzHUN-0

return : 
```JSON
{ "error": { "code": "build_not_deployed", "message": "Build '4TX6kuAsEVKjfJ7ogpzHUN-0' has not been deployed", "args": { "bid": "4TX6kuAsEVKjfJ7ogpzHUN-0" } } }
```

So even after trying to run 

`npm run build && npm run deploy`

the problem still persist when launched with npm run start 

Note that the generated url https://warpjs-9cl7yqib4buxmkbep876tmy00.storage.googleapis.com/index.html
is OK 

NPM version 6.9.0
Node version 10.16.0

**Comment by jpl-scale** [comment]
Thanks for your report.

First, your deployment is just fine. Everything goes well.

For development mode, you need to use in your browser an URL with `localhost` or `127.0.0.1`. Using your local ip address is not possible. Could you confirm us that it is the issue?

**Comment by dezmou** [comment]
Yes this is the issue
I need to use the npm run start script on a different machine than the machine where chrome is launched 

Do you think this maybe possible one day ?

**Comment by jpl-scale** [comment]
Yes, definitely. This will probably be an option. We are waiting the end of the Beta program to decide.

I close the issue right now, does not hesitate to re-open if you want to discuss that.

**Comment by dezmou** [comment]
BTW I managed to use a workaround by searching and replacing "localhost" in node_modules/@warpsjs/engine/lib/engine-dev.js

**Comment by jpl-scale** [comment]
Could you please explain us your workflow? Why do you need something like that?

**Comment by dezmou** [comment]
I am used to use webpack-dev-server on external mode with --host 0.0.0.0 for two reason : 

My desktop machine where chrome is running is using windows, I am used to code on a local linux server because executing code on windows is hell. 
I use the remote-ssh vs-code extension to code on another machine on the network.

The second reason is I want the live-reload to also refresh the chrome on my mobile device which is also connected to http://my-device:8080, perfect for mobile-first development

**Comment by jpl-scale** [comment]
I understand. Thanks a lot for your time.
