### ISSUE TITLE
TypeError: Cannot read property 'watchRun' of undefined

### ISSUE THREAD

**Issue by cnabot-scale** [WarpJS/beta#2]
Got this error when trying to run a project using webpack 3. Warp is only compatible with webpack 4

**Comment by jpl-scale** [comment]
Please, update the doc.

**Comment by NicolasPennec** [comment]
Doc updated with the prerequisite: https://warpjs.dev/docs/getting-started#install-warpjs-dependencies

> Please note that the WarpJS Webpack plugin is only compatible with Webpack 4.
