### ISSUE TITLE
Unclear error at runtime when WarpifyPlugin is missing

### ISSUE THREAD

**Issue by scajegou** [WarpJS/beta#3]
After adding the warpify plugin to my webpack config, I forgot to stop webpack and redo a npm start.
I had included the engine import and init in my code, and it failed with the following:

```
ReferenceError: warpEngineConfig is not defined
```

which is not very helpful

**Comment by jpl-scale** [comment]
Fixed in @warpjs/webpack-plugin@1.1.1
