### ISSUE TITLE
npm start triggers an ENOENT error

### ISSUE THREAD

**Issue by domscale** [WarpJS/beta#6]
I followed the steps of the Hello World guide and got the following error when launching the CL npm start

**hello-world dom$ npm start**

> warpjs-webpack-template@1.0.0 start /Users/dom/src/hello-world
> webpack-dev-server --open

sh: webpack-dev-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! warpjs-webpack-template@1.0.0 start: `webpack-dev-server --open`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the warpjs-webpack-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additionallogging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dom/.npm/_logs/2020-02-14T17_14_53_623Z-debug.log

**--- here is the forementioned log ---**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle warpjs-webpack-template@1.0.0~prestart: warpjs-webpack-template@1.0.0
6 info lifecycle warpjs-webpack-template@1.0.0~start: warpjs-webpack-template@1.0.0
7 verbose lifecycle warpjs-webpack-template@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle warpjs-webpack-template@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dom/src/hello-world/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle warpjs-webpack-template@1.0.0~start: CWD: /Users/dom/src/hello-world
10 silly lifecycle warpjs-webpack-template@1.0.0~start: Args: [ '-c', 'webpack-dev-server --open' ]
11 info lifecycle warpjs-webpack-template@1.0.0~start: Failed to exec start script
12 verbose stack Error: warpjs-webpack-template@1.0.0 start: `webpack-dev-server --open`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid warpjs-webpack-template@1.0.0
14 verbose cwd /Users/dom/src/hello-world
15 verbose Darwin 19.3.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v10.15.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error warpjs-webpack-template@1.0.0 start: `webpack-dev-server --open`
23 error spawn ENOENT
24 error Failed at the warpjs-webpack-template@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by cnabot-scale** [comment]
This is likely because webpack-dev-server is not installed. Install it with `npm install` and try to launch it again.
